/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.View;

import java.awt.Color;
import java.text.ParseException;

/**
 *
 * @author gitre
 */
public class LoginUserView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginUserView() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        goToRegisterUserButton = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        appNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        setLocation(new java.awt.Point(350, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setLabelFor(emailInput);
        emailLabel.setText("E-mail");
        mainPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 40, -1));

        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        mainPanel.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 190, 30));

        loginLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        loginLabel.setText("Login");
        mainPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        passwordLabel.setLabelFor(passwordInput);
        passwordLabel.setText("Senha");
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, -1));

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        mainPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 190, 30));

        loginButton.setText("Entrar");
        mainPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 90, 30));

        goToRegisterUserButton.setBackground(new java.awt.Color(204, 204, 204));
        goToRegisterUserButton.setText("Cadastre-se");
        goToRegisterUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRegisterUserButtonActionPerformed(evt);
            }
        });
        mainPanel.add(goToRegisterUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, 30));

        registerLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        registerLabel.setText("Não possui uma conta?");
        mainPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        appNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appNameLabel.setText("Adote.Pet");
        mainPanel.add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void goToRegisterUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRegisterUserButtonActionPerformed
        src.View.RegisterUserView registerUserView = new src.View.RegisterUserView();
        registerUserView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToRegisterUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton goToRegisterUserButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel registerLabel;
    // End of variables declaration//GEN-END:variables

}
