/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.View;

import java.awt.Color;
import java.text.ParseException;

/**
 *
 * @author gitre
 */
public class RegisterPetView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public RegisterPetView() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        registerLabel = new javax.swing.JLabel();
        breedLabel = new javax.swing.JLabel();
        addPetButton = new javax.swing.JButton();
        appNameLabel = new javax.swing.JLabel();
        specieLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        colorLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        specieComboBox = new javax.swing.JComboBox<>();
        breedComboBox = new javax.swing.JComboBox<>();
        colorComboBox = new javax.swing.JComboBox<>();
        heightSpinner = new javax.swing.JSpinner();
        weightLabel = new javax.swing.JLabel();
        weightSpinner = new javax.swing.JSpinner();
        dateOfBirthLabel = new javax.swing.JLabel();
        dateOfBirthInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        setLocation(new java.awt.Point(350, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setLabelFor(nameInput);
        nameLabel.setText("Nome ");
        mainPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 40, -1));

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        mainPanel.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 190, 30));

        registerLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        registerLabel.setText("Adicionar Pet");
        mainPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        breedLabel.setLabelFor(breedComboBox);
        breedLabel.setText(" Raça");
        mainPanel.add(breedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 40, -1));

        addPetButton.setText("Salvar");
        mainPanel.add(addPetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 90, 30));

        appNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appNameLabel.setText("Adote.Pet");
        mainPanel.add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        specieLabel.setLabelFor(specieComboBox);
        specieLabel.setText(" Espécie");
        mainPanel.add(specieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        genderLabel.setLabelFor(genderComboBox);
        genderLabel.setText("Gênero");
        mainPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 190, 30));

        colorLabel.setLabelFor(colorComboBox);
        colorLabel.setText("Cor");
        mainPanel.add(colorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 20, -1));

        heightLabel.setLabelFor(heightSpinner);
        heightLabel.setText("Altura (cm)");
        mainPanel.add(heightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 60, -1));

        specieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato" }));
        specieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specieComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(specieComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 30));

        breedComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Golden Retriever", "Pug", "Basset", "Bulldog", "Husky Siberiano", "Chihuahua", "Poodle", "Beagle", "Outro" }));
        breedComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(breedComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, 30));

        colorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marrom", "Branco", "Preto", "Cinza", "Outro" }));
        colorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(colorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 30));
        mainPanel.add(heightSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 322, 190, 30));

        weightLabel.setLabelFor(weightSpinner);
        weightLabel.setText("Peso (kg)");
        mainPanel.add(weightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 50, -1));
        mainPanel.add(weightSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 190, 30));

        dateOfBirthLabel.setLabelFor(dateOfBirthInput);
        dateOfBirthLabel.setText("Data de Nascimento");
        mainPanel.add(dateOfBirthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, -1));

        dateOfBirthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthInputActionPerformed(evt);
            }
        });
        mainPanel.add(dateOfBirthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 190, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorComboBoxActionPerformed

    private void breedComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breedComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breedComboBoxActionPerformed

    private void specieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specieComboBoxActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void dateOfBirthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPetView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPetButton;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JComboBox<String> breedComboBox;
    private javax.swing.JLabel breedLabel;
    private javax.swing.JComboBox<String> colorComboBox;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField dateOfBirthInput;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox<String> specieComboBox;
    private javax.swing.JLabel specieLabel;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JSpinner weightSpinner;
    // End of variables declaration//GEN-END:variables

}
