/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.View;

import main.View.LoginUserView;

import java.awt.Color;
import java.text.ParseException;

/**
 *
 * @author gitre
 */
public class RegisterUserView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public RegisterUserView() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        registerLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        goToLoginUserButton = new javax.swing.JButton();
        appNameLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        cpfLabel = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        cpfInput = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberInput = new javax.swing.JTextField();
        dateOfBirthInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        setLocation(new java.awt.Point(350, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setLabelFor(emailInput);
        emailLabel.setText("E-mail");
        mainPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 40, -1));

        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        mainPanel.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 190, 30));

        registerLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        registerLabel.setText("Cadastro");
        mainPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        dateOfBirthLabel.setLabelFor(dateOfBirthInput);
        dateOfBirthLabel.setText("Data de Nascimento");
        mainPanel.add(dateOfBirthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, -1));

        registerButton.setText("Registrar");
        mainPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 90, 30));

        goToLoginUserButton.setBackground(new java.awt.Color(204, 204, 204));
        goToLoginUserButton.setText("Voltar para o login");
        goToLoginUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginUserButtonActionPerformed(evt);
            }
        });
        mainPanel.add(goToLoginUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, 30));

        appNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appNameLabel.setText("Adote.Pet");
        mainPanel.add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        mainPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 30));

        passwordLabel.setLabelFor(passwordInput);
        passwordLabel.setText("Senha ");
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        genderLabel.setLabelFor(genderComboBox);
        genderLabel.setText("Gênero");
        mainPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outro", "Prefiro não dizer" }));
        genderComboBox.setSelectedIndex(3);
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 190, 30));

        cpfLabel.setLabelFor(cpfInput);
        cpfLabel.setText("CPF");
        mainPanel.add(cpfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 30, -1));

        addressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressInputActionPerformed(evt);
            }
        });
        mainPanel.add(addressInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 190, 30));

        addressLabel.setLabelFor(addressInput);
        addressLabel.setText("Endereço");
        mainPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 50, -1));

        cpfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfInputActionPerformed(evt);
            }
        });
        mainPanel.add(cpfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 30));

        phoneNumberLabel.setLabelFor(phoneNumberInput);
        phoneNumberLabel.setText("Celular/Telefone");
        mainPanel.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 90, -1));

        phoneNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberInputActionPerformed(evt);
            }
        });
        mainPanel.add(phoneNumberInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 190, 30));

        dateOfBirthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthInputActionPerformed(evt);
            }
        });
        mainPanel.add(dateOfBirthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void goToLoginUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginUserButtonActionPerformed
        LoginUserView loginUserView = new LoginUserView();
        loginUserView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToLoginUserButtonActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void addressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressInputActionPerformed

    private void cpfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfInputActionPerformed

    private void phoneNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberInputActionPerformed

    private void dateOfBirthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JTextField cpfInput;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField dateOfBirthInput;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton goToLoginUserButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneNumberInput;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    // End of variables declaration//GEN-END:variables

}
